apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: kubectl-gaggle
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/honk-ci/kubectl-gaggle/releases/download/v0.1.0/kubectl-gaggle_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./kubectl-gaggle"
      to: "."
    bin: "kubectl-gaggle"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/honk-ci/kubectl-gaggle/releases/download/v0.1.0/kubectl-gaggle_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./kubectl-gaggle"
      to: "."
    bin: "kubectl-gaggle"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/honk-ci/kubectl-gaggle/releases/download/v0.1.0/kubectl-gaggle_windows_amd64.zip
    sha256: ""
    files:
    - from: "/kubectl-gaggle.exe"
      to: "."
    bin: "kubectl-gaggle.exe"
  shortDescription: A new plugin
  homepage: https://github.com/honk-ci/kubectl-gaggle
  caveats: |
    Usage:
      $ kubectl kubectl-gaggle

    For additional options:
      $ kubectl kubectl-gaggle --help
      or https://github.com/honk-ci/kubectl-gaggle/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
